apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrs
  labels:
    app: nrs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nrs
  template:
    metadata:
      labels:
        app: nrs
    spec:
      containers:
        - name: nrs
          image: devzgr007/node-recoding-system:v1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: nrs-configmap
                  key: SPRING_APPLICATION_NAME
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: nrs-configmap
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nrs-configmap
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: nrs-configmap
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB
              valueFrom:
                configMapKeyRef:
                  name: nrs-configmap
                  key: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB
---
apiVersion: v1
kind: Service
metadata:
  name: nrs
spec:
  selector:
    app: nrs
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081